/* ---------- DATA: official ICAI section weightages ---------- */
const PAPERS = {
  fr:{name:"Financial Reporting",color:"var(--fr)",dot:"#5b9dd6",dur:"3 hrs · 100 marks · 70% descriptive + 30% MCQ",
    sections:[
      {t:"Section I · Introduction & Framework",wt:"10–15%",p:"lo",note:"Conceptual base. Ind AS framework + Div II Sch III presentation. Reads fast, underpins everything.",ch:["Intro to General Purpose FS (Ind AS)","Statutory provisions & applicability criteria","Division II of Schedule III, Companies Act 2013","Conceptual Framework for Financial Reporting"]},
      {t:"Section II · Revenue Recognition",wt:"5–10%",p:"lo",note:"Ind AS 115 five-step model. Small weight but appears almost every attempt.",ch:["Ind AS 115 Revenue from Contracts","AS 7 / AS 9 vs Ind AS 115 comparison"]},
      {t:"Section III · Assets & Liabilities",wt:"15–25%",p:"hi",note:"Highest FR weight. Master Ind AS 116 (Leases), 36 (Impairment), 19 (Employee Benefits) — these carry the section.",ch:["Ind AS 2 Inventories","Ind AS 16 Property, Plant & Equipment","Ind AS 116 Leases","Ind AS 23 Borrowing Costs","Ind AS 36 Impairment of Assets","Ind AS 38 Intangible Assets","Ind AS 40 Investment Property","Ind AS 105 Non-current Assets Held for Sale","Ind AS 19 Employee Benefits","Ind AS 37 Provisions & Contingencies","Ind AS 12 Income Taxes","Ind AS 8 Accounting Policies & Estimates"]},
      {t:"Section IV · Disclosures",wt:"15–20%",p:"med",note:"Standard-heavy, presentation-based. Related Party (24) and EPS (33) are the frequent scorers.",ch:["Ind AS 24 Related Party Disclosures","Ind AS 33 Earnings per Share","Ind AS 108 Operating Segments","Ind AS 20 Government Grants","Ind AS 102 Share Based Payment","Ind AS 41 Agriculture"]},
      {t:"Section V · Financial Instruments",wt:"10–15%",p:"lo",note:"Conceptually hardest area. Classification/measurement + hedge accounting. High effort per mark — don't over-invest but don't skip.",ch:["Ind AS 32 Presentation","Ind AS 109 Financial Instruments","Ind AS 107 Disclosures","Classification & Measurement of FA/FL","Derivatives & Embedded Derivatives","Recognition & Derecognition","Hedge Accounting"]},
      {t:"Section VI · Group Accounting",wt:"10–20%",p:"med",note:"Consolidation is a guaranteed large question. Practice CFS prep repeatedly — Ind AS 103 & 110 are the core.",ch:["Ind AS 103 Business Combinations","Ind AS 110 Consolidated FS","Ind AS 111 Joint Arrangements","Ind AS 27 Separate FS","Ind AS 28 Associates & JVs","Ind AS 112 Disclosure of Interests"]},
      {t:"Section VII · First Time Adoption",wt:"5–10%",p:"lo",note:"Ind AS 101 only. Rule-heavy but self-contained — reliable marks if memorised.",ch:["Ind AS 101 First-time Adoption"]},
      {t:"Section VIII · Analysis, Ethics & Technology",wt:"5–10%",p:"lo",note:"Newer additions. Easy marks — analysis of FS, ethics in accounting, technology.",ch:["Analysis of Financial Statements (Ind AS)","Ethics with Accounting Concepts","Technology and Accounting","Evolution of Accounting in tech environment"]}
    ],
    tips:["Don't just solve sums — read the paragraphs of the Ind AS. ICAI lifts tricky lines from the standard text to frame questions.","Presentation of Notes to Accounts wins marks. Format matters as much as the number.","Section III + VI ≈ 40% together. If time is tight, these two are non-negotiable.","Application questions ask 'why' behind the treatment — be able to justify, not just compute.","Ind AS 116, 36, 109, 103, 110 are the repeat offenders. Front-load them."],
    res:[["ICAI BoS Knowledge Portal","https://www.icai.org/post/bos-knowledge-portal"],["FR Past Papers","https://capapers.com/ca-final-practice-papers/financial-reporting"]]
  },
  afm:{name:"Advanced Financial Management",color:"var(--afm)",dot:"#c77dff",dur:"3 hrs · 100 marks · 70% descriptive + 30% MCQ",
    sections:[
      {t:"Section I · Financial Policy, Risk & Capital Budgeting",wt:"8–15%",p:"lo",note:"Conceptual opener + VaR and advanced capital budgeting. Theory-heavy relative to rest of paper.",ch:["Financial Policy & Corporate Strategy","Role of CFO in Value Creation","Strategic Decision Making Framework","Financial goals vs Sustainable Growth","Risk Management","Value at Risk (VaR)","Advanced Capital Budgeting Decisions","Impact of Inflation on Capital Budgeting","Replacement & Abandonment decisions","Adjusted Present Value"]},
      {t:"Section II · Security Analysis, Valuation & Portfolio",wt:"20–30%",p:"hi",note:"Core scoring block. Security & equity/bond valuation, portfolio theory. Practice until mechanical.",ch:["Fundamental Analysis","Technical Analysis","Efficient Market Hypothesis","Security Valuation","Equity Risk Premium","Valuation of Equity Shares","Valuation of Preference Shares","Valuation of Debentures/Bonds","Portfolio Management basics","Portfolio Theory (Markowitz)","CAPM","Portfolio Performance Evaluation","Bond Portfolio & Duration"]},
      {t:"Section III · Securitization, Derivatives & Forex",wt:"20–30%",p:"hi",note:"Biggest scoring area with Section II. Master Option Greeks, Black-Scholes, and forex hedging cold.",ch:["Securitization","Tokenization","Mutual Funds","Hedge Funds","Derivatives Analysis & Valuation","Forwards, Futures & Options","Option Pricing & Option Greeks","Black-Scholes Model","Credit Derivatives","Interest Rate Derivatives","Commodity Derivatives","Forex — Exchange Rate Determination","Forex Exposure & Risk Management","Forex Hedging strategies","Currency & Interest Rate Swaps"]},
      {t:"Section IV · International Financial Management",wt:"20–25%",p:"med",note:"Consistently large. International Capital Budgeting + Interest Rate Risk are the anchors.",ch:["International Capital Budgeting","Offshore Investment Strategies","Raising Funds Internationally","Sovereign Funds","International Financial Centre (GIFT City)","International Working Capital Mgmt","Multinational Cash Management","Interest Rate Risk Management","International Sources of Finance","ADR/GDR & foreign listings","Foreign Investment Analysis","Cross-border taxation impact on FM","Political & country risk"]},
      {t:"Section V · Business Valuation",wt:"10–15%",p:"lo",note:"Valuation models incl. EVA/MVA/SVA and CAPM/APT. Overlaps Section II — leverage that.",ch:["Conceptual Framework of Valuation","Assets Based Valuation Model","Earning Based Models","Cash Flow Based Models","CAPM & Arbitrage Pricing Theory","Relative Valuation","EVA, MVA, SVA","Going & Non-Going Concern Valuation","Valuation of Intangibles","Valuation of distressed firms","Chop-shop / sum-of-parts","Valuation for M&A"]},
      {t:"Section VI · M&A and Startup Finance",wt:"2–5%",p:"lo",note:"Smallest weight. Restructuring, LBOs, SPACs, startup finance. Read once, don't over-prepare.",ch:["Mergers, Acquisitions & Restructuring","Takeover Defensive Tactics","Reverse Merger","Divestitures & Demerger","Leveraged Buyouts","Cross Border Mergers","SPACs","Startup Finance","Venture Capital methods","Corporate restructuring numericals"]}
    ],
    tips:["Practice numerical problems DAILY. AFM is 80%+ sums — reading theory won't build the speed you need.","Sections II + III together = 40–60% of the paper. If you own these, you're at pass level before touching the rest.","Present formulas + workings clearly. Examiners award step marks even when the final answer slips.","Keep a formula sheet (Greeks, Black-Scholes, forex parity, portfolio) and revise it every single day.","Time per question is tight — solve past papers under a clock, not open-ended."],
    res:[["ICAI BoS Knowledge Portal","https://www.icai.org/post/bos-knowledge-portal"],["AFM Past Papers","https://capapers.com/ca-final-practice-papers/advanced-financial-management"]]
  },
  aud:{name:"Advanced Auditing, Assurance & Professional Ethics",color:"var(--aud)",dot:"#4fb783",dur:"3 hrs · 100 marks · 70% descriptive + 30% MCQ",
    sections:[
      {t:"Section I · Standards on Auditing (SAs)",wt:"45–55%",p:"hi",note:"The single highest-weighted section in ALL of CA Final. Roughly half the paper. SA number + name recall is the backbone — this is where the exam is won or lost.",ch:["SQC 1 Quality Control","SA 200 Overall Objectives","SA 210 Terms of Engagement","SA 220 Quality Control for Audit","SA 230 Audit Documentation","SA 240 Fraud","SA 250 Laws & Regulations","SA 260 Communication with TCWG","SA 265 Deficiencies in Internal Control","SA 299 Joint Audit","SA 300 Planning","SA 315 Risk of Material Misstatement","SA 320 Materiality","SA 330 Responses to Risks","SA 402 Service Organisation","SA 450 Evaluation of Misstatements","SA 500 Audit Evidence","SA 501 / 505 / 510 Specific Evidence","SA 520 Analytical Procedures","SA 530 Audit Sampling","SA 540 Accounting Estimates","SA 550 Related Parties","SA 560 / 570 / 580 Events, Going Concern, Reps","SA 600 / 610 / 620 Using others' work","SA 700–720 Audit Report series"]},
      {t:"Section III · Specialised Audits",wt:"17–24%",p:"med",note:"Second scoring pillar. Bank/NBFC/PSU audits + consolidated FS + propriety/performance audit. Application-heavy.",ch:["Group Audits & SA 600","Audit of Consolidated FS","Audit of Banks","Audit of NBFCs","Audit of PSUs","Propriety Audit","Performance Audit","Comprehensive Audit","Audit of Insurance Companies","Audit under Fiscal Laws","Audit of Co-operative Societies","Cost Audit essentials","Audit Committee & Governance"]},
      {t:"Section V · Professional Ethics & Liabilities",wt:"17–24%",p:"med",note:"Memory-heavy, high-scoring. CA Act 1949 Schedules + Code of Ethics. Reliable marks if the misconduct provisions are memorised.",ch:["Code of Ethics as per IESBA","Code of Ethics under CA Act 1949","Fundamental Principles","Threats, Evaluation & Safeguards","Chartered Accountants Act 1949 — Schedules","CA Regulations 1988"]},
      {t:"Section II · Digital Auditing & Assurance",wt:"3–6%",p:"lo",note:"Small but easy. CAAT, data analytics, AI & remote auditing. Quick read, easy marks.",ch:["Auditing Digitally & Digital Auditing","CAAT (Computer Assisted Audit Techniques)","Data Analytics in Auditing","Artificial Intelligence in Auditing","Remote Auditing"]},
      {t:"Section IV · Emerging Areas",wt:"3–6%",p:"lo",note:"Newest, smallest. SDG + ESG assurance. Two topics — learn them, bank the marks.",ch:["Sustainable Development Goals (SDG)","ESG Assurance"]}
    ],
    tips:["Section I (SAs) is ~half the paper. Blind-recall test: list every SA by number + one-line gist. If you can't, you're not ready.","Ethics is pure memory + presentation. Learn the Schedules to the CA Act verbatim — clauses are quoted in answers.","Write in ICAI's language. Audit is marked on keywords and standard phrasing, not paraphrase.","Section I + III + V ≈ 85% of marks. Nail these three; the rest is bonus.","Practice case-study style questions — the paper tests applying SAs to scenarios, not just definitions.","Scan the current-attempt RTP/MTP: audit repeats questions more than any other Group 1 paper."],
    res:[["ICAI BoS Knowledge Portal","https://www.icai.org/post/bos-knowledge-portal"],["Audit Past Papers","https://capapers.com/ca-final-practice-papers/advanced-auditing"]]
  }
};

/* ---------- Revision plan ---------- */
const PLAN=[
  {tag:"Foundation · Weeks 1–4",h:"First full pass — concepts + standards",p:"One clean read-through per paper, building the skeleton. Don't chase perfection — chase coverage.",li:["FR: lock Section III & VI first (highest weight), then work outward.","AFM: start daily numerical practice immediately — Sections II & III every day.","Audit: SAs from day one. Aim to recall all SA numbers + names by end of Week 4.","End each week: one topic-wise test on what you covered. Log confidence in this tracker."]},
  {tag:"Consolidation · Weeks 5–8",h:"Second pass — application + past papers",p:"Shift from learning to solving. This is where marks are actually built.",li:["Solve past CA Final papers topic-by-topic (last 4–5 attempts, New Scheme only).","FR & Audit: move to full-length case-study questions.","AFM: timed problem sets — speed is the constraint, not knowledge.","Revisit every confidence-1 (red) chapter flagged here. No red chapters allowed to survive this phase."]},
  {tag:"Revision · Weeks 9–11",h:"Third pass — rapid recall + weak areas",p:"Compress. Fast-track notes, formula sheets, SA lists. Cover-recall-check, not re-read.",li:["Daily: AFM formula sheet + Audit SA list, blind recall.","FR: summary notes for each Ind AS — one page per standard.","Solve current-attempt RTPs (released ~2 months before exam) — repeats are common.","Attempt MTP Series I under exam conditions when ICAI releases it."]},
  {tag:"Final Sprint · Weeks 12–13",h:"Full mocks + exam simulation",p:"Nov 2/4/6 — FR, then AFM, then Audit. Simulate that exact rhythm.",li:["Full 3-hour timed mocks for each paper. Self-mark against ICAI suggested answers.","MTP Series II (released ~1 month out) — treat as dress rehearsal.","Final revision of only high-weight sections + all red/amber chapters.","Sleep, logistics, admit card. Walk in rested — recall degrades when exhausted."]}
];

/* ---------- How to pass ---------- */
const RULES=[
  ["01","Clear the paper, then the group","Pass = 40 in EACH paper AND 150/300 aggregate. One paper at 38 sinks the whole group even if the other two are 70s. Protect the floor on every paper — no zeros, no skipped sections."],
  ["02","Weightage is your map","Section I of Audit alone is ~50 marks. Sections II+III of AFM are ~40–60. FR Sections III+VI are ~40. Hours should follow marks. Study by weight, not by chapter order."],
  ["03","70% descriptive + 30% MCQ","30 marks per paper are MCQs — often application-based, negative-marking-free but time-pressured. Practice ICAI MCQs; they're free marks people leave on the table."],
  ["04","ICAI language wins marks","Especially in Audit & FR theory. Examiners reward standard terminology and clause references. Learn to write like the study material, not like a summary."],
  ["05","Past papers + RTP + MTP are the syllabus","Everything official and free on the BoS Knowledge Portal. Repeats are common. Solving 4–5 recent attempts per paper is worth more than a fifth read of a textbook."],
  ["06","Presentation & step marks","Show workings, label clearly, format notes. Partial credit is real — a well-presented wrong answer often beats a bare correct number."],
  ["07","Attempt every question","Blank = guaranteed zero. Even a partial attempt on a tough question can pull the 2–3 marks that cross 40. Never leave a question untouched."],
  ["08","It's a retake — study to retrieve","She's seen this before. Reading for understanding wastes the edge. Cover, recall, check. Speed of recall under pressure is the real exam skill."]
];



export { PAPERS, PLAN, RULES };
